# Let's look at our data

We are only focusing on five candidates using data from the 2016 primary elections: Bernie Sanders, Donald Trump, Hillary Clinton, john Kasich, and Ted Cruz. 

`NaN` values were replaced by 0, but maybe replace later if they cause issues. 

In [15]:
import numpy as np
import pandas as pd  


#Read the csv file
data = pd.read_csv('primary_data.csv')

print(data)

        state      county  Bernie Sanders  Donald Trump  Hillary Clinton  \
0     Alabama     Autauga             544          5387             2387   
1     Alabama     Baldwin            2694         23618             5290   
2     Alabama     Barbour             222          1710             2567   
3     Alabama        Bibb             246          1959              942   
4     Alabama      Blount             395          7390              564   
...       ...         ...             ...           ...              ...   
4200  Wyoming  Sweetwater              12             0               10   
4201  Wyoming       Teton               9           238               84   
4202  Wyoming       Uinta               5             0                4   
4203  Wyoming    Washakie               1             0                2   
4204  Wyoming      Weston               1           454              940   

      John Kasich  Ted Cruz  
0             421      2482  
1            2987      8571

# This is Plurality


In [3]:
#sum the total number of votes
total_votes = data.sum(axis = 0, numeric_only= True)

#print results
print(total_votes.sort_values(axis = 0, ascending = False))


Hillary Clinton    17508677
Donald Trump       15659872
Bernie Sanders     11959102
Ted Cruz            8024089
John Kasich         3975015
dtype: int64


# Borda Count

In [16]:
#Just get the numerical data
num_data = data.iloc[:,2:]


#print(np.shape(data.iloc[:,2:]))

# Convert the data to a numpy matrix without the col headers
numpy_mat = num_data.to_numpy()

# Convert that to a DataFrame to get row max
mat = pd.DataFrame(numpy_mat)

# Find shape of the num_data matrix
row, col = np.shape(mat)

# Allocate data to count the instance of candidate placements 
borda_count_mat = np.zeros((col,col))

#print(np.shape(borda_count_mat))

# Loop to find row_max and count placements
for i in range(row):
    for j in range(col):
        
        #Find the row max location
        row_max_loc = mat.idxmax(axis = 1)
        location = row_max_loc[i]
        
        #Add 1 to the  candidate, place in the borda matrix        
        borda_count_mat[location, j] += 1
        
        #Replace the row_max with a -1
        numpy_mat[i,location] = -1
            
print(borda_count_mat)



[[1393.  663.  526. 1070.  553.]
 [1519. 1470. 1048.  166.    2.]
 [ 887. 1153. 1235.  516.  414.]
 [  34.  121.  503. 1608. 1939.]
 [ 372.  798.  893.  845. 1297.]]


# Issue

## Why did I convert to numpy and then back to data frame? 

If I use the original data frame, `idxmax` outputs the header which is a string `"Hillary Clinton"` instead of the `int`, which does not allow us to index the value into the borda matrix

In [17]:
#get the row_max location
row_max = num_data.idxmax(axis = 1)

print(row_max)


print('\n\n' + row_max[2])

0       Bernie Sanders
1       Bernie Sanders
2       Bernie Sanders
3       Bernie Sanders
4       Bernie Sanders
             ...      
4200    Bernie Sanders
4201    Bernie Sanders
4202    Bernie Sanders
4203    Bernie Sanders
4204    Bernie Sanders
Length: 4205, dtype: object


Bernie Sanders


In [13]:
#convert the data to a numpy matrix without the col headers
numpy_mat = num_data.to_numpy()

#convert that to a DataFrame to get row max
mat = pd.DataFrame(numpy_mat)

numpy_row_max = mat.idxmax(axis = 1)

print(numpy_row_max)

0       1
1       1
2       2
3       1
4       1
       ..
4200    0
4201    4
4202    0
4203    2
4204    2
Length: 4205, dtype: int64
